### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by sksembhi** [mattrobenolt/imgur-cli#1]
SK$ imgur
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/bin/imgur
  Reason: image not found
Trace/BPT trap: 5

**Comment by mattrobenolt** [comment]
I need to rewrite into something not Swift. Turns out, Swift is the worst language.

**Comment by rossnomann** [comment]
RIIR!
